### ISSUE TITLE
Throws Syntax Error in IE 11 and Edge 41

### ISSUE THREAD

**Issue by pratik-trianz** [Fausto95/aws-s3#1]
Here is the error i got

Object.defineProperty(__webpack_exports__, \"__esModule\", { value: true });\n\n// CONCATENATED MODULE: ./node_modules/react-s3/lib/Signature.js\nconst Crypto = __webpack_require__(1193);\n\nclass Signature {\n    static getSignature(config, date, policyBase64) {\n        const getSignatureKey = (Crypto, key, dateStamp, regionName) => {\n            const kDate = Crypto.HmacSHA256(dateStamp, \"AWS4\" + key);\n            const kRegion = Crypto.HmacSHA256(regionName, kDate);\n            const kService = Crypto.HmacSHA256('s3', kRegion);\n            const kSigning = Crypto.HmacSHA256(\"aws4_request\", kService);\n            return kSigning;\n        };\n        const signature = policyEncoded => {\n            return Crypto.HmacSHA256(policyEncoded, getSignatureKey(Crypto, config.secretAccessKey, date, config.region, \"s3\")).toString(Crypto.enc.Hex);\n        };\n        return signature(policyBase64);\n    }\n}\n// EXTERNAL MODULE: ./node_modules/react-s3/lib/Policy.js\nvar Policy = __webpack_require__(1217);\n\n// EXTERNAL MODULE: ./node_modules/react-s3/lib/Date.js\nvar lib_Date = __webpack_require__(558);\n\n// CONCATENATED MODULE: ./node_modules/react-s3/lib/ReactS3.js\n\n\n\n\nclass ReactS3_ReactS3 {\n    static upload(file, config) {\n        const fd = new FormData();\n        const key = `${config.albumName}/` + file.name;\n        const url = `https://${config.bucketName}.s3.amazonaws.com/`;\n        fd.append('key', key);\n        fd.append('acl', 'public-read');\n        fd.append('Content-Type', file.type);\n        fd.append('x-amz-meta-uuid', '14365123651274');\n        fd.append('x-amz-server-side-encryption', 'AES256');\n        fd.append('X-Amz-Credential', `${config.accessKeyId}/${lib_Date[\"b\" /* dateYMD */]}/${config.region}/s3/aws4_request`);\n        fd.append('X-Amz-Algorithm', 'AWS4-HMAC-SHA256');\n        fd.append('X-Amz-Date', lib_Date[\"c\" /* xAmzDate */]);\n        fd.append('x-amz-meta-tag', '');\n        fd.append('Policy', Policy[\"a\" /* default */].getPolicy(config));\n        fd.append('X-Amz-Signature', Signature.getSignature(config, lib_Date[\"b\" /* dateYMD */], Policy[\"a\" /* default */].getPolicy(config)));\n        fd.append(\"file\", file);\n        return new Promise(async (resolve, reject) => {\n            const errorHandler = fn => {\n                return fn.then(data => [null, data]).catch(err => [err]);\n            };\n            const uploadResult = async () => {\n                let err, result;\n                [err, result] = await errorHandler(fetch(url, {\n                    method: 'post',\n                    headers: {\n                        fd\n                    },\n                    body: fd\n                }));\n                if (err) reject(err);\n                resolve({\n                    bucket: config.bucketName,\n                    key: `${config.albumName}/${file.name}`,\n                    location: `${url}${config.albumName}/${file.name}`,\n                    result: result\n                });\n            };\n            uploadResult();\n        });\n    }\n    static delete(fileName, config) {\n        const fd = new FormData();\n        const url = `https://${config.bucketName}.s3-${config.region}.amazonaws.com/${config.albumName}/${fileName}`;\n        fd.append('Date', lib_Date[\"c\" /* xAmzDate */]);\n        fd.append('X-Amz-Date', lib_Date[\"c\" /* xAmzDate */]);\n        fd.append('Authorization', Signature.getSignature(config, lib_Date[\"b\" /* dateYMD */], Policy[\"a\" /* default */].getPolicy(config)));\n        fd.append('Content-Type', 'text/plain');\n        return new Promise(async (resolve, reject) => {\n            const errorHandler = fn => {\n                return fn.then(data => [null, data]).catch(err => [err]);\n            };\n            const deleteResult = async () => {\n                let err, result;\n                [err, result] = await errorHandler(fetch(url, {\n                    method: 'delete',\n                    headers: {\n                        fd\n                    }\n                }));\n                if (err) reject(err);\n                resolve({\n                    ok: result.ok,\n                    status: result.status,\n                    message: 'File Deleted',\n                    fileName: fileName\n                });\n            };\n            deleteResult();\n        });\n    }\n}\n/* harmony default export */ var lib_ReactS3 = __webpack_exports__[\"default\"] = (ReactS3_ReactS3);//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvcmVhY3QtczMvbGliL1NpZ25hdHVyZS5qcz80ZmViIiwid2VicGFjazovLy8uL25vZGVfbW9kdWxlcy9yZWFjdC1zMy9saWIvUmVhY3RTMy5qcz9iMGFmIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7OztBQUFBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxDOzs7Ozs7OztBQ2hCQTtBQUNBO0FBQzJDOztBQUUzQztBQUNBO0FBQ0E7QUFDQSx1QkFBdUIsaUJBQWlCO0FBQ3hDLCtCQUErQixrQkFBa0I7QUFDakQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLHlDQUF5QyxtQkFBbUIsR0FBRyw0QkFBUSxHQUFHLGNBQWM7QUFDeEY7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxxQkFBcUI7QUFDckI7QUFDQSxpQkFBaUI7QUFDakI7QUFDQTtBQUNBO0FBQ0EsNEJBQTRCLGlCQUFpQixHQUFHLFVBQVU7QUFDMUQsaUNBQWlDLElBQUksRUFBRSxpQkFBaUIsR0FBRyxVQUFVO0FBQ3JFO0FBQ0EsaUJBQWlCO0FBQ2pCO0FBQ0E7QUFDQSxTQUFTO0FBQ1Q7QUFDQTtBQUNBO0FBQ0EsK0JBQStCLGtCQUFrQixNQUFNLGNBQWMsaUJBQWlCLGlCQUFpQixHQUFHLFNBQVM7QUFDbkg7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsaUJBQWlCO0FBQ2pCO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLGlCQUFpQjtBQUNqQjtBQUNBO0FBQ0EsU0FBUztBQUNUO0FBQ0E7QUFDQSIsImZpbGUiOiIxMTkyLmpzIiwic291cmNlc0NvbnRlbnQiOlsiY29uc3QgQ3J5cHRvID0gcmVxdWlyZSgnY3J5cHRvLWpzJyk7XG5cbmV4cG9ydCBkZWZhdWx0IGNsYXNzIFNpZ25hdHVyZSB7XG4gICAgc3RhdGljIGdldFNpZ25hdHVyZShjb25maWcsIGRhdGUsIHBvbGljeUJhc2U2NCkge1xuICAgICAgICBjb25zdCBnZXRTaWduYXR1cmVLZXkgPSAoQ3J5cHRvLCBrZXksIGRhdGVTdGFtcCwgcmVnaW9uTmFtZSkgPT4ge1xuICAgICAgICAgICAgY29uc3Qga0RhdGUgPSBDcnlwdG8uSG1hY1NIQTI1NihkYXRlU3RhbXAsIFwiQVdTNFwiICsga2V5KTtcbiAgICAgICAgICAgIGNvbnN0IGtSZWdpb24gPSBDcnlwdG8uSG1hY1NIQTI1NihyZWdpb25OYW1lLCBrRGF0ZSk7XG4gICAgICAgICAgICBjb25zdCBrU2VydmljZSA9IENyeXB0by5IbWFjU0hBMjU2KCdzMycsIGtSZWdpb24pO1xuICAgICAgICAgICAgY29uc3Qga1NpZ25pbmcgPSBDcnlwdG8uSG1hY1NIQTI1NihcImF3czRfcmVxdWVzdFwiLCBrU2VydmljZSk7XG4gICAgICAgICAgICByZXR1cm4ga1NpZ25pbmc7XG4gICAgICAgIH07XG4gICAgICAgIGNvbnN0IHNpZ25hdHVyZSA9IHBvbGljeUVuY29kZWQgPT4ge1xuICAgICAgICAgICAgcmV0dXJuIENyeXB0by5IbWFjU0hBMjU2KHBvbGljeUVuY29kZWQsIGdldFNpZ25hdHVyZUtleShDcnlwdG8sIGNvbmZpZy5zZWNyZXRBY2Nlc3NLZXksIGRhdGUsIGNvbmZpZy5yZWdpb24sIFwiczNcIikpLnRvU3RyaW5nKENyeXB0by5lbmMuSGV4KTtcbiAgICAgICAgfTtcbiAgICAgICAgcmV0dXJuIHNpZ25hdHVyZShwb2xpY3lCYXNlNjQpO1xuICAgIH1cbn1cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL25vZGVfbW9kdWxlcy9yZWFjdC1zMy9saWIvU2lnbmF0dXJlLmpzXG4vLyBtb2R1bGUgaWQgPSBudWxsXG4vLyBtb2R1bGUgY2h1bmtzID0gIiwiaW1wb3J0IFNpZ25hdHVyZSBmcm9tICcuL1NpZ25hdHVyZSc7XG5pbXBvcnQgUG9saWN5IGZyb20gJy4vUG9saWN5JztcbmltcG9ydCB7IGRhdGVJU09TdHJpbmcsIHhBbXpEYXRlLCBkYXRlWU1EIH0gZnJvbSAnLi9EYXRlJztcblxuY2xhc3MgUmVhY3RTMyB7XG4gICAgc3RhdGljIHVwbG9hZChmaWxlLCBjb25maWcpIHtcbiAgICAgICAgY29uc3QgZmQgPSBuZXcgRm9ybURhdGEoKTtcbiAgICAgICAgY29uc3Qga2V5ID0gYCR7Y29uZmlnLmFsYnVtTmFtZX0vYCArIGZpbGUubmFtZTtcbiAgICAgICAgY29uc3QgdXJsID0gYGh0dHBzOi8vJHtjb25maWcuYnVja2V0TmFtZX0uczMuYW1hem9uYXdzLmNvbS9gO1xuICAgICAgICBmZC5hcHBlbmQoJ2tleScsIGtleSk7XG4gICAgICAgIGZkLmFwcGVuZCgnYWNsJywgJ3B1YmxpYy1yZWFkJyk7XG4gICAgICAgIGZkLmFwcGVuZCgnQ29udGVudC1UeXBlJywgZmlsZS50eXBlKTtcbiAgICAgICAgZmQuYXBwZW5kKCd4LWFtei1tZXRhLXV1aWQnLCAnMTQzNjUxMjM2NTEyNzQnKTtcbiAgICAgICAgZmQuYXBwZW5kKCd4LWFtei1zZXJ2ZXItc2lkZS1lbmNyeXB0aW9uJywgJ0FFUzI1NicpO1xuICAgICAgICBmZC5hcHBlbmQoJ1gtQW16LUNyZWRlbnRpYWwnLCBgJHtjb25maWcuYWNjZXNzS2V5SWR9LyR7ZGF0ZVlNRH0vJHtjb25maWcucmVnaW9ufS9zMy9hd3M0X3JlcXVlc3RgKTtcbiAgICAgICAgZmQuYXBwZW5kKCdYLUFtei1BbGdvcml0aG0nLCAnQVdTNC1ITUFDLVNIQTI1NicpO1xuICAgICAgICBmZC5hcHBlbmQoJ1gtQW16LURhdGUnLCB4QW16RGF0ZSk7XG4gICAgICAgIGZkLmFwcGVuZCgneC1hbXotbWV0YS10YWcnLCAnJyk7XG4gICAgICAgIGZkLmFwcGVuZCgnUG9saWN5JywgUG9saWN5LmdldFBvbGljeShjb25maWcpKTtcbiAgICAgICAgZmQuYXBwZW5kKCdYLUFtei1TaWduYXR1cmUnLCBTaWduYXR1cmUuZ2V0U2lnbmF0dXJlKGNvbmZpZywgZGF0ZVlNRCwgUG9saWN5LmdldFBvbGljeShjb25maWcpKSk7XG4gICAgICAgIGZkLmFwcGVuZChcImZpbGVcIiwgZmlsZSk7XG4gICAgICAgIHJldHVybiBuZXcgUHJvbWlzZShhc3luYyAocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICAgICAgICBjb25zdCBlcnJvckhhbmRsZXIgPSBmbiA9PiB7XG4gICAgICAgICAgICAgICAgcmV0dXJuIGZuLnRoZW4oZGF0YSA9PiBbbnVsbCwgZGF0YV0pLmNhdGNoKGVyciA9PiBbZXJyXSk7XG4gICAgICAgICAgICB9O1xuICAgICAgICAgICAgY29uc3QgdXBsb2FkUmVzdWx0ID0gYXN5bmMgKCkgPT4ge1xuICAgICAgICAgICAgICAgIGxldCBlcnIsIHJlc3VsdDtcbiAgICAgICAgICAgICAgICBbZXJyLCByZXN1bHRdID0gYXdhaXQgZXJyb3JIYW5kbGVyKGZldGNoKHVybCwge1xuICAgICAgICAgICAgICAgICAgICBtZXRob2Q6ICdwb3N0JyxcbiAgICAgICAgICAgICAgICAgICAgaGVhZGVyczoge1xuICAgICAgICAgICAgICAgICAgICAgICAgZmRcbiAgICAgICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICAgICAgYm9keTogZmRcbiAgICAgICAgICAgICAgICB9KSk7XG4gICAgICAgICAgICAgICAgaWYgKGVycikgcmVqZWN0KGVycik7XG4gICAgICAgICAgICAgICAgcmVzb2x2ZSh7XG4gICAgICAgICAgICAgICAgICAgIGJ1Y2tldDogY29uZmlnLmJ1Y2tldE5hbWUsXG4gICAgICAgICAgICAgICAgICAgIGtleTogYCR7Y29uZmlnLmFsYnVtTmFtZX0vJHtmaWxlLm5hbWV9YCxcbiAgICAgICAgICAgICAgICAgICAgbG9jYXRpb246IGAke3VybH0ke2NvbmZpZy5hbGJ1bU5hbWV9LyR7ZmlsZS5uYW1lfWAsXG4gICAgICAgICAgICAgICAgICAgIHJlc3VsdDogcmVzdWx0XG4gICAgICAgICAgICAgICAgfSk7XG4gICAgICAgICAgICB9O1xuICAgICAgICAgICAgdXBsb2FkUmVzdWx0KCk7XG4gICAgICAgIH0pO1xuICAgIH1cbiAgICBzdGF0aWMgZGVsZXRlKGZpbGVOYW1lLCBjb25maWcpIHtcbiAgICAgICAgY29uc3QgZmQgPSBuZXcgRm9ybURhdGEoKTtcbiAgICAgICAgY29uc3QgdXJsID0gYGh0dHBzOi8vJHtjb25maWcuYnVja2V0TmFtZX0uczMtJHtjb25maWcucmVnaW9ufS5hbWF6b25hd3MuY29tLyR7Y29uZmlnLmFsYnVtTmFtZX0vJHtmaWxlTmFtZX1gO1xuICAgICAgICBmZC5hcHBlbmQoJ0RhdGUnLCB4QW16RGF0ZSk7XG4gICAgICAgIGZkLmFwcGVuZCgnWC1BbXotRGF0ZScsIHhBbXpEYXRlKTtcbiAgICAgICAgZmQuYXBwZW5kKCdBdXRob3JpemF0aW9uJywgU2lnbmF0dXJlLmdldFNpZ25hdHVyZShjb25maWcsIGRhdGVZTUQsIFBvbGljeS5nZXRQb2xpY3koY29uZmlnKSkpO1xuICAgICAgICBmZC5hcHBlbmQoJ0NvbnRlbnQtVHlwZScsICd0ZXh0L3BsYWluJyk7XG4gICAgICAgIHJldHVybiBuZXcgUHJvbWlzZShhc3luYyAocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICAgICAgICBjb25zdCBlcnJvckhhbmRsZXIgPSBmbiA9PiB7XG4gICAgICAgICAgICAgICAgcmV0dXJuIGZuLnRoZW4oZGF0YSA9PiBbbnVsbCwgZGF0YV0pLmNhdGNoKGVyciA9PiBbZXJyXSk7XG4gICAgICAgICAgICB9O1xuICAgICAgICAgICAgY29uc3QgZGVsZXRlUmVzdWx0ID0gYXN5bmMgKCkgPT4ge1xuICAgICAgICAgICAgICAgIGxldCBlcnIsIHJlc3VsdDtcbiAgICAgICAgICAgICAgICBbZXJyLCByZXN1bHRdID0gYXdhaXQgZXJyb3JIYW5kbGVyKGZldGNoKHVybCwge1xuICAgICAgICAgICAgICAgICAgICBtZXRob2Q6ICdkZWxldGUnLFxuICAgICAgICAgICAgICAgICAgICBoZWFkZXJzOiB7XG4gICAgICAgICAgICAgICAgICAgICAgICBmZFxuICAgICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgfSkpO1xuICAgICAgICAgICAgICAgIGlmIChlcnIpIHJlamVjdChlcnIpO1xuICAgICAgICAgICAgICAgIHJlc29sdmUoe1xuICAgICAgICAgICAgICAgICAgICBvazogcmVzdWx0Lm9rLFxuICAgICAgICAgICAgICAgICAgICBzdGF0dXM6IHJlc3VsdC5zdGF0dXMsXG4gICAgICAgICAgICAgICAgICAgIG1lc3NhZ2U6ICdGaWxlIERlbGV0ZWQnLFxuICAgICAgICAgICAgICAgICAgICBmaWxlTmFtZTogZmlsZU5hbWVcbiAgICAgICAgICAgICAgICB9KTtcbiAgICAgICAgICAgIH07XG4gICAgICAgICAgICBkZWxldGVSZXN1bHQoKTtcbiAgICAgICAgfSk7XG4gICAgfVxufVxuZXhwb3J0IGRlZmF1bHQgUmVhY3RTMztcblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL25vZGVfbW9kdWxlcy9yZWFjdC1zMy9saWIvUmVhY3RTMy5qc1xuLy8gbW9kdWxlIGlkID0gbnVsbFxuLy8gbW9kdWxlIGNodW5rcyA9ICJdLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///1192\n"

**Comment by Fausto95** [comment]
Hey, 
I just tried uploading using Edge 42 and it worked !
Can you try it again ?

**Comment by pratik-trianz** [comment]
Yes. It works in higher versions. but can not use in lower versions of IE or edge.

**Comment by Fausto95** [comment]
Thank you, I'll try to fix it !

**Comment by Fausto95** [comment]
Fixed !
