### ISSUE TITLE
How to Use GUIDs for image uploads ? 

### ISSUE THREAD

**Issue by siamraj** [Fausto95/aws-s3#10]
There is a bug that relates to how images are stored in S3. For all images, the name of the image is used to store it in S3. Which means let's say I am adding a pet husky and I am uploading an image with name mypet.jpeg.

Later if you adding a new image for yourself with your pet image mypet.jpeg. Then it will override the previous image uploaded by me.  Thats why we should be using a GUID for images.

When uploading images, remove the name of the image that is uploaded and instead use a GUID for the S3 image name.

example if I am uploading mypet.jpg then change the file name to 09dacb08-378d-408c-abb1-379b558cd604.jpeg and then upload to S3. This should be how it needs to be done for all image uploads.

**Comment by Fausto95** [comment]
Very interesting, I will be fixing this!
