### ISSUE TITLE
Meteor  installation issue 

### ISSUE THREAD

**Issue by surajsundariyatweedl** [Fausto95/aws-s3#12]
After  installation to "meteor npm install --save react-s3" my application showing error meteorInstallation not  found and many  more please help

**Comment by Fausto95** [comment]
Use  `meteor npm install --save aws-s3` instead.

**Comment by surajsundariyatweedl** [comment]
still it show the same error in chrome console 

Uncaught SyntaxError: Unexpected identifier
es5-shim.js?hash=c070fc7aa1536cb75430d62c9dad8eaffe2b3716:17 Uncaught TypeError: Cannot read property '**meteorInstall**' of undefined
    at es5-shim.js?hash=c070fc7aa1536cb75430d62c9dad8eaffe2b3716:17
    at es5-shim.js?hash=c070fc7aa1536cb75430d62c9dad8eaffe2b3716:2792
(anonymous) @ es5-shim.js?hash=c070fc7aa1536cb75430d62c9dad8eaffe2b3716:17
(anonymous) @ es5-shim.js?hash=c070fc7aa1536cb75430d62c9dad8eaffe2b3716:2792
promise.js?hash=5178f5c21c0108b730984960833975420cc0c7a2:17 Uncaught TypeError: **Cannot read property 'meteorInstall' of undefined**
    at promise.js?hash=5178f5c21c0108b730984960833975420cc0c7a2:17
    at promise.js?hash=5178f5c21c0108b730984960833975420cc0c7a2:585
(anonymous) @ promise.js?hash=5178f5c21c0108b730984960833975420cc0c7a2:17
(anonymous) @ promise.js?hash=5178f5c21c0108b730984960833975420cc0c7a2:585
babel-runtime.js?hash=13782baeb18e96869f18571ab602f1508a0a6621:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at babel-runtime.js?hash=13782baeb18e96869f18571ab602f1508a0a6621:17
    at babel-runtime.js?hash=13782baeb18e96869f18571ab602f1508a0a6621:176
(anonymous) @ babel-runtime.js?hash=13782baeb18e96869f18571ab602f1508a0a6621:17
(anonymous) @ babel-runtime.js?hash=13782baeb18e96869f18571ab602f1508a0a6621:176
ecmascript-runtime-client.js?hash=236033036aa3b0629009d2af14113e2413052567:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at ecmascript-runtime-client.js?hash=236033036aa3b0629009d2af14113e2413052567:17
    at ecmascript-runtime-client.js?hash=236033036aa3b0629009d2af14113e2413052567:110
(anonymous) @ ecmascript-runtime-client.js?hash=236033036aa3b0629009d2af14113e2413052567:17
(anonymous) @ ecmascript-runtime-client.js?hash=236033036aa3b0629009d2af14113e2413052567:110
ejson.js?hash=3af8c8d41c63ca01c1c9698a677bc5ae971ff3b2:18 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at ejson.js?hash=3af8c8d41c63ca01c1c9698a677bc5ae971ff3b2:18
    at ejson.js?hash=3af8c8d41c63ca01c1c9698a677bc5ae971ff3b2:861
(anonymous) @ ejson.js?hash=3af8c8d41c63ca01c1c9698a677bc5ae971ff3b2:18
(anonymous) @ ejson.js?hash=3af8c8d41c63ca01c1c9698a677bc5ae971ff3b2:861
diff-sequence.js?hash=15014d7b1e11c05111a386992e684ab1d3cc4158:18 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at diff-sequence.js?hash=15014d7b1e11c05111a386992e684ab1d3cc4158:18
    at diff-sequence.js?hash=15014d7b1e11c05111a386992e684ab1d3cc4158:297
(anonymous) @ diff-sequence.js?hash=15014d7b1e11c05111a386992e684ab1d3cc4158:18
(anonymous) @ diff-sequence.js?hash=15014d7b1e11c05111a386992e684ab1d3cc4158:297
geojson-utils.js?hash=e9d235fa7a29b6bcb50d7ad0b05751fa169fcc8b:17 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at geojson-utils.js?hash=e9d235fa7a29b6bcb50d7ad0b05751fa169fcc8b:17
    at geojson-utils.js?hash=e9d235fa7a29b6bcb50d7ad0b05751fa169fcc8b:442
(anonymous) @ geojson-utils.js?hash=e9d235fa7a29b6bcb50d7ad0b05751fa169fcc8b:17
(anonymous) @ geojson-utils.js?hash=e9d235fa7a29b6bcb50d7ad0b05751fa169fcc8b:442
id-map.js?hash=c7aea8dfa2bf46ff2ae0aa6c6cf09e36abc61d07:18 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at id-map.js?hash=c7aea8dfa2bf46ff2ae0aa6c6cf09e36abc61d07:18
    at id-map.js?hash=c7aea8dfa2bf46ff2ae0aa6c6cf09e36abc61d07:123
(anonymous) @ id-map.js?hash=c7aea8dfa2bf46ff2ae0aa6c6cf09e36abc61d07:18
(anonymous) @ id-map.js?hash=c7aea8dfa2bf46ff2ae0aa6c6cf09e36abc61d07:123
random.js?hash=189ef930765405ef87a31a621407fc34447b8756:18 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
    at random.js?hash=189ef930765405ef87a31a621407fc34447b8756:18
    at random.js?hash=189ef930765405ef87a31a621407fc34447b8756:371
(anonymous) @ random.js?hash=189ef930765405ef87a31a621407fc34447b8756:18
(anonymous) @ random.js?hash=189ef930765405ef87a31a621407fc34447b8756:371
mongo-id.js?hash=345d169d517353f8146292b4abd24061721f8b26:17 Uncaught TypeError: Cannot read property 'EJSON' of undefined
    at mongo-id.js?hash=345d169d517353f8146292b4abd24061721f8b26:17
    at mongo-id.js?hash=345d169d517353f8146292b4abd24061721f8b26:142

**Comment by Fausto95** [comment]
Hi there, everything might be working now if you install the latest version(1.5.0)

**Comment by Fausto95** [comment]
I'll be checking it.
Thanks for your reporting

**Comment by Evert-jvv** [comment]
+1 same issue

**Comment by Fausto95** [comment]
@surajsundariyatweedl & @Evert-jvv I just fixed your issues. 
Install the latest version `1.5.5` by doing `npm i aws-s3`
