### ISSUE TITLE
RE: deletion of file issue

### ISSUE THREAD

**Issue by ankitjain200292** [Fausto95/aws-s3#15]
Hi I have been facing issue while deleting the images from the s3 as in the uploadFIle function file is uploaded by not adding the region name is the URL but during the delete file it's taking the region name in the URL so that leads to URL mismatch and the file is not found on the URL. 

Any help is appreciated 

Thanks

**Comment by ankit-gartner** [comment]
@Fausto95 Can you please help me on this ?

**Comment by ankitjain200292** [comment]
@Fausto95 can you help me out ?

**Comment by Fausto95** [comment]
Hi @ankitjain200292, I'll check it.
Thanks for filling the issue!

**Comment by vutsalsinghal** [comment]
Yes, I'm facing same issue while deleting file. Are there any updates yet?

(Keep up the good work!)

**Comment by wvicioso** [comment]
Same issue regarding region and miss-matching url when trying to process a file deletion.

**Comment by wvicioso** [comment]
https://github.com/Fausto95/aws-s3/pull/26 this fixes the issue. Please merge @Fausto95
