### ISSUE TITLE
npm run build failed due to minify code 

### ISSUE THREAD

**Issue by weikee94** [Fausto95/aws-s3#20]
When i trying to run npm build, it prompts error about failed to minify the code from this file:
![screen shot 2018-10-08 at 12 00 25 pm](https://user-images.githubusercontent.com/13563834/46592063-d5efed00-caf1-11e8-85f1-5b95d384cac6.png)

from the error i guessing because the file using Class syntax which is es2016 and the create-react-app didnt compile it so i added babel-loader but still showing me the same error

my babel settings:
![screen shot 2018-10-08 at 12 04 59 pm](https://user-images.githubusercontent.com/13563834/46592129-69c1b900-caf2-11e8-931e-af76c22b785e.png)

Any help would be greatly appreciated. Thank you.

**Comment by Fausto95** [comment]
Hi @weikee94. 
You are using the old package!
Please install the newer one by doing `npm install -S aws-s3`.

**Comment by weikee94** [comment]
> Hi @weikee94.
> You are using the old package!
> Please install the newer one by doing `npm install -S aws-s3`.

Thanks. It works now.
