### ISSUE TITLE
Failed to minify the code from this file ./node_modules/react-s3/lib/ReactS3.js:6

### ISSUE THREAD

**Issue by kapilgundawar** [Fausto95/aws-s3#21]
Hi Team,

Iam facing this issue when iam using

npm run build (for my production)

Failed to minify the code from this file

 ./node_modules/react-s3/lib/ReactS3.js:6

Read more here: http://bit.ly/2tRViJ9

Iam not able to get what is wrong it would be great help if someone help me in this regard

**Comment by Fausto95** [comment]
Hi @kapilgundawar!
You're using the old package. Please install the newer one by running: `npm install -S aws-s3`!

**Comment by kapilgundawar** [comment]
Hi @Fausto95 
Updated the package to aws-s3 now working fine
Thanks for the quick response :+1:
