### ISSUE TITLE
Problem with UglifyJs

### ISSUE THREAD

**Issue by mss-deepak** [Fausto95/aws-s3#23]
**ERROR in crosstab-portal-1.0.0.js from UglifyJs
Unexpected token: keyword (const) [./node_modules/react-s3/lib/Date.js:1,7][xxx-xxx-1.0.0.js:10995,0]**

I am not able to build the application. I am facing above error when I run build command.
Any solution for this?

**Comment by Fausto95** [comment]
The library react-s3 is deprecated. Please install the new on by 
```shell
npm install --save was-s3
```
