### ISSUE TITLE
Could not find a declaration file for module 'aws-s3'

### ISSUE THREAD

**Issue by dotamir** [Fausto95/aws-s3#28]
Hi. I installed the package and when I want to import it, I got this error:

```Could not find a declaration file for module 'aws-s3'. '/home/user/project/node_modules/aws-s3/cjs/aws-s3.js' implicitly has an 'any' type.
  Try `npm install @types/aws-s3` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-s3';```

What's wrong here?

**Comment by Fausto95** [comment]
This project isn't built with Typescript, so if you're trying to use it in a TS project, you skip the type-checking for it!

**Comment by bbruneau** [comment]
Looks like you've got it in TS now. Can you expose your types in the npm package?

**Comment by dotamir** [comment]
It's ok and it was a simple question. Thank you and I'll close it.
