### ISSUE TITLE
Use aws-s3 in aws-china.

### ISSUE THREAD

**Issue by WillWuCaminer** [Fausto95/aws-s3#30]
Hi, I'm a developer from China. 

Our team want to upload files to aws-china with aws-s3. But we found that the url in S3Client.js does not apply to China.  After trying, we found that we need to change the url to use this：

```
const url = `https://${config.bucketName}.s3.${config.region}.amazonaws.com.cn/`
```

We don't know if there are other countries with local aws. So maybe we can't solve this problem through PR. We especially hope that you can help us solve this problem. Thank you very much! 

I look forward to hearing from you.

**Comment by Fausto95** [comment]
Hi, thanks for filling this issue.
Could you open a PR to fix the problem?
