### ISSUE TITLE
S3Client.uploadFile is not a function

### ISSUE THREAD

**Issue by afolabiabass** [Fausto95/aws-s3#40]
I have tried figuring out why I am getting this error not sure what else to do. Setup is consistent with suggested setup, any ideas?

**Comment by kprocks86** [comment]
I do have the same problem with version 2.0.2

**Comment by kprocks86** [comment]
@afolabiabass 
I'm using it as in component so i made a new raw .js file and write an function that can execute this s3Client.uploadFile this willl work for me.

**Comment by afolabiabass** [comment]
@kprocks86 i think the issue was with the way I was passing the config data.
