### ISSUE TITLE
uploaded file name changed 

### ISSUE THREAD

**Issue by DevenSharma** [Fausto95/aws-s3#53]
when i upload a file on s3 bucket  it rename the file.

for example - 
file name-   **abc.xlsx**
in response the uploaded file name is changed 
like-   **my-awesome-file.xlsx.vnd.openxmlformats-officedocument.spreadsheetml.sheet**

i have also checked its not issue of s3 bucket when i directly upload file on s3 bucket it upload with same name. 

its an issue it should upload with same name

**Comment by Fausto95** [comment]
Since https://github.com/Fausto95/aws-s3/pull/52 was merged, we now change the file name when uploading it into s3 bucket, see https://github.com/Fausto95/aws-s3/issues/10
