### ISSUE TITLE
How to give file a default name

### ISSUE THREAD

**Issue by Fernandocgomez** [Fausto95/aws-s3#68]
I am getting this error when I use the first filename argument 

`const filename = 'hello-world.jpg' `

`const S3Client = new S3(config); `

` upload = (e) => {
    console.log(e.target.files[0])
    
    S3Client.uploadFile(filename, e.target.files[0])
    .then(data => console.log(data))
    .catch(err => console.error(err))
  } `

Thanks, guys

**Comment by Fausto95** [comment]
Make sure that you're using the latest version et check out the README file for more info about the usage

```js
S3Client.uploadFile(file, newFileName)
.then(data => console.log(data))
.catch(err => console.error(err))
```

**Comment by Fernandocgomez** [comment]
Thank you, man. I had my syntax wrong.
