### ISSUE TITLE
Problem with loading module

### ISSUE THREAD

**Issue by Milosh1** [Fausto95/aws-s3#7]
Hi, when i installed module for a first time everything was fine, but when I turned off my application and turn on again I got this error: 
![screenshot from 2018-04-27 09-58-28](https://user-images.githubusercontent.com/20223986/39351601-4df1f6b6-4a02-11e8-97b2-ab838db035e6.png)
I tried to delete module and install it again (with command **npm install --save react-s3**) but bug is not fixed. Any help?

**Comment by Fausto95** [comment]
Hi, I don't know why this is happening. I'll try to reproduce the same to fix it!
Thanks for filling the issue !

**Comment by Fausto95** [comment]
I just tried and everything is working perfectly here, are you CRA or something else ?
Here a working exemple https://codesandbox.io/s/l9233mz349. 
Please let me now if it stills bugging!

**Comment by Milosh1** [comment]
Hello, 
Thanks for answering, I was a busy but I find what is a problem. In this plugin you use import instead require and my node version (8.9.4) is not accept this. Witch version of node you use ?

**Comment by Fausto95** [comment]
Hi, 
I use the v9+

**Comment by Fausto95** [comment]
Sorry guys. 
I just published a new version which transpiles to ES5, you can now use it everywhere!

**Comment by Fausto95** [comment]
@Milosh1  & @dilipkumar2k6  I just fixed your issues. 
Install the latest version `1.5.5` by doing `npm i aws-s3`
