### ISSUE TITLE
Access has been blocked by CORS policy.

### ISSUE THREAD

**Issue by user09876090** [Fausto95/aws-s3#75]
Whenever I try to upload an image in my s3 bucket I am getting the following error

`Access to fetch at 'https://lab-profile-images.s3.amazonaws.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I am using the [react-s3](https://www.npmjs.com/package/react-s3) library. In my s3 configuration I'm passing 

- bucketName
- region
- accessKeyId
- secretAccessKey
- successActionStatus

I have not passed the dirName. Is it compulsory to pass dirName? Because in the documentation of [react-s3](https://www.npmjs.com/package/react-s3) here, they have mentioned **dirName** as **Optional**  in the file upload example.

I have also tried to disable chrome web security and tried to upload but still no luck. The CORS access is enable on server side.
Anyone can guide me ?

![Screenshot 2020-07-24 at 16 48 00](https://user-images.githubusercontent.com/46704464/88389271-9205cf00-cdcf-11ea-9e7f-9ee09dbb042d.png)

**Comment by mdnmnahmed** [comment]
> Whenever I try to upload an image in my s3 bucket I am getting the following error
> 
> `Access to fetch at 'https://lab-profile-images.s3.amazonaws.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
> 
> I am using the [react-s3](https://www.npmjs.com/package/react-s3) library. In my s3 configuration I'm passing
> 
> * bucketName
> * region
> * accessKeyId
> * secretAccessKey
> * successActionStatus
> 
> I have not passed the dirName. Is it compulsory to pass dirName? Because in the documentation of [react-s3](https://www.npmjs.com/package/react-s3) here, they have mentioned **dirName** as **Optional** in the file upload example.
> 
> I have also tried to disable chrome web security and tried to upload but still no luck. The CORS access is enable on server side.
> Anyone can guide me ?
> 
> ![Screenshot 2020-07-24 at 16 48 00](https://user-images.githubusercontent.com/46704464/88389271-9205cf00-cdcf-11ea-9e7f-9ee09dbb042d.png)

# go to your s3 bucket, inside inside permissions section click on CORS configuration tab and change some CORS rules like:-

<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    **<AllowedHeader>*</AllowedHeader>**
</CORSRule>

**Comment by user09876090** [comment]
@mdnmnahmed Thanks!!

**Comment by mdnmnahmed** [comment]
@user09876090 my pleasure...😊
