### ISSUE TITLE
Problem with ErrorThrower

### ISSUE THREAD

**Issue by ad-hok** [Fausto95/aws-s3#9]
Hi, i'm trying to upload a file, but i got an error

Error: Must provide a filename in order to delete anything in your bucket

The problem is in the ErrorThrower class, specifically in fileName param, using the uploadFile method

Thanks

**Comment by Fausto95** [comment]
Hi, I'll fix this bug today. 
Thanks

**Comment by Fausto95** [comment]
Just fixed the bug! 
Make sure you update to the v1.4.1
